app/images/urls.py
'''
Observations: Open access archive app for Las Cumbres Observatory Global Telescope Network
Copyright (C) 2014-2015 LCOGT

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
'''
from django.conf.urls import patterns

urlpatterns = patterns('',

)

app/observations/urls.py
# -*- coding: utf-8 -*-
'''
Observations: Open access archive app for Las Cumbres Observatory Global Telescope Network
Copyright (C) 2014-2015 LCOGT

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
'''
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from images.views import search, view_group, view_username, index, view_object, \
    view_avm, view_category, view_category_list, view_site, view_telescope, identity, \
    view_observation, view_site_slideshow, view_map
from images.archive import frame_lookup, recent_observations_page
from images.rti_images import ImageDetail

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


handler500 = 'images.views.server_error'

urlpatterns = [
    url(r'^$', index, name='home'),
    url(r'^search/$',  search,name="search"),

    url(r'^recent/$', recent_observations_page, name='show_recent'),

    # url(r'^object/(?P<object>[a-zA-Z \+\-\.0-9]+)/$', view_object),
    # url(r'^object/$', index),
    # url(r'^o/(?P<object>[a-zA-Z \+\-\.0-9]+)/$', view_object),
    #
    # url(r'^category/(?P<avm>[0-9\.]+)/$', view_avm,name='show_avm'),
    # url(r'^category/(?P<category>\w+)/$', view_category,name='category_show'),
    # url(r'^category/$', view_category_list,name='category_list'),
    # url(r'^c/(?P<avm>[0-9\.]+)/$', view_avm),
    # url(r'^c/(?P<category>\w+)/$', view_category),
    #
    # url(r'^map/$', view_map),

    url(r'^frame/(?P<frameid>[0-9]+)/$', frame_lookup, name='frame'),
    url(r'^image/(?P<pk>[0-9]+)/$', ImageDetail.as_view(), name='image-detail'),
    url(r'^admin/', include(admin.site.urls)),

  ]

if not settings.PRODUCTION:
    urlpatterns += staticfiles_urlpatterns()

app/images/forms.py
'''
Observations: Open access archive app for Las Cumbres Observatory Global Telescope Network
Copyright (C) 2014-2015 LCOGT

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
'''
from django import forms
from datetime import datetime, date
from images.models import Site, Filter


class SearchForm(forms.Form):
    sites = [(s.code, s.name) for s in Site.objects.all()]
    filters = [(f.code, f.name) for f in Filter.objects.all().distinct()]
    sites.append(('', 'Select a site...'))
    filters.append(('', 'Select a filter...'))

    query = forms.CharField(label='Name of astronomical object:', required=False)
    startdate = forms.DateTimeField(required=False)
    enddate = forms.DateTimeField(required=False)
    alldates = forms.BooleanField(required=False)
    sites = forms.ChoiceField(choices=sites, required=False)
    filters = forms.ChoiceField(choices=filters, required=False)
    exposure = forms.FloatField(widget=forms.TextInput(attrs={'size': '5'}), required=False)
    exposurecondition = forms.ChoiceField(choices=(
        ('gt', 'greater than'), ('lt', 'less than'), ('eq', 'equals')), required=False)
    offset = forms.IntegerField(required=False)

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.fields['startdate'].widget.attrs['placeholder'] = 'YYYY-MM-DD'
        self.fields['enddate'].widget.attrs['placeholder'] = 'YYYY-MM-DD'
        self.fields['startdate'].initial = "2014-04-01"
        self.fields['enddate'].initial = datetime.now().strftime("%Y-%m-%d")
        self.fields['exposurecondition'].initial = 'gt'
        self.fields['alldates'].initial = False

    def clean_startdate(self):
        if self.cleaned_data['startdate']:
            data = self.cleaned_data['startdate']
            if data < datetime(2004, 9, 1):
                raise forms.ValidationError(
                    "Our records only go back to 1 Sept 2004")
            return data
        else:
            return self.cleaned_data['startdate']

app/images/views.py
  # -*- coding: utf-8 -*-
'''
Observations: Open access archive app for Las Cumbres Observatory Global Telescope Network
Copyright (C) 2014-2015 LCOGT

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
'''
from datetime import date, timedelta, datetime
from django.conf import settings
from django.contrib.admin.models import LogEntry, CHANGE
from django.contrib.sites.models import Site as DjSite
from django.core import serializers, urlresolvers
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.db import connections
from django.db.models import Count, Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render_to_response, render
from django.template import RequestContext
from django.utils.encoding import smart_unicode
from email.utils import parsedate_tz
from images.forms import SearchForm
from images.models import Site, Telescope, Filter, Image, ObservationStats, wistime_format
from images.utils import parsetime, dmstodegrees, hmstodegrees, hmstohours, datestamp, \
    filter_list, filter_props, filter_link, filter_name, hexangletodec, l, binMonths
from images.archive import recent_observations, search_archive, get_auth_headers, \
    search_archive_data
from images.lookups import categories, categorylookup
from images.users import user_look_up, look_up_org_names, collate_org_names
from string import replace
import json
import math
import re
from bs4 import BeautifulSoup
import requests
import logging

logger = logging.getLogger('images')

n_per_line = 6
n_per_page = 18
base_url = "https://lco.global/observations/"

def server_error(request):
    # one of the things 'render' does is add 'STATIC_URL' to
    # the context, making it available from within the template.
    response = render(request, '500.html')
    response.status_code = 500
    return response


def index(request):

    sites = Site.objects.all()
    telescopes = Telescope.objects.all()
    latest = recent_observations()

    return render(request, 'images/index.html', {'latest': latest,
                                                    'sites': sites,
                                                    'telescopes': telescopes,
                                                    'categories': categories})


def view_group(request, mode, format=None):
    input = input_params(request)
    sites = Site.objects.all()

    if(mode == "recent"):
        obs = build_recent_observations(n_per_page)
        input['title'] = "Recent Observations from LCOGT"
        input['link'] = 'recent'
        input['live'] = 300
        input['description'] = 'Recent observations from the Las Cumbres Observatory Global Telescope'
    elif(mode == "popular"):
        obstats = ObservationStats.objects.all().order_by(
            '-views')[:n_per_page]
        n = obstats.count()
        obs = []
        for o in obstats:
            obs.append(o.image)
        obs = build_observations(obs)
        input['title'] = "All-time Most Viewed Observations at LCOGT"
        input['link'] = 'popular'
        input[
            'description'] = 'Most popular observations from the Las Cumbres Observatory Global Telescope'
    elif(mode == "trending"):
        obstats = ObservationStats.objects.all().order_by(
            '-weight')[:n_per_page]
        n = obstats.count()
        obs = []
        for o in obstats:
            obs.append(o.image)
        obs = build_observations(obs)
        input['title'] = "Trending Observations at LCOGT"
        input['link'] = 'trending'
        input[
            'description'] = 'Trending observations from the Las Cumbres Observatory Global Telescope'

    input['observations'] = len(obs)
    input['perpage'] = n_per_page

    if input['doctype'] == "json" or format == 'json':
        return view_json(request, build_observations_json(obs), input)
    elif input['doctype'] == "kml":
        return view_kml(request, obs, input)
    elif input['doctype'] == "rss":
        return view_rss(request, obs, input)
    else:
        data = {'input': input, 'link': input[
            'link'], 'obs': obs, 'n': len(obs)}
        if input['slideshow']:
            return render_to_response('images/slideshow.html', data, context_instance=RequestContext(request))
        else:
            return render_to_response('images/group.html', data, context_instance=RequestContext(request))


def since(request):
    since = request.GET.get('since', '')
    if since != '':
        try:
            sd = parsedate_tz(since)
            sd = "%s%02d%02d%02d%02d%02d" % (
                sd[0], sd[1], sd[2], sd[3], sd[4], sd[5])
        except:
            sd = ''
    return sd


def search_rtiarchive(form):
    obs = []
    n = -1
    obs = Image.objects.all()
    if form['query']:
        query_string = form['query'].replace('(','').replace(')','')
        obs = obs.filter(objectname__icontains=(query_string))
    if form['sites'] in ('ogg', 'coj'):
        obs = obs.filter(telescope__site__code=form['sites'])
    if form['filters']:
        obs = obs.filter(filter=form['filters'])
    if form['startdate'] and form['enddate']:
        obs = obs.filter(dateobs__gte=form['startdate'], dateobs__lte=form['enddate'])
    if form['enddate']:
        obs = obs.filter(dateobs__lte=form['enddate'])
    if form['exposure']:
        try:
            form['exposure'] = float(form['exposure'])
            if(form['exposurecondition'] == 'gt'):
                obs = obs.filter(exposuresecs__gt=form['exposure'])
            elif(form['exposurecondition'] == 'lt'):
                obs = obs.filter(exposuresecs__lt=form['exposure'])
            else:
                obs = obs.filter(exposuresecs=form['exposure'])
        except:
            form['exposure'] = 0

    obs = obs.order_by('-dateobs')
    return obs


def search(request, format=None):
    page_data = input_params(request)
    if not request.GET:
        form = SearchForm()
        return render(request, 'images/search.html', {'form': form})
    else:
        #page_data ={}
        form = SearchForm(request.GET)
        if form.is_valid():
            lastobs = request.GET.get('lastobs', None)
            if lastobs:
                if "T" in lastobs:
                    lastobs = datetime.strptime(lastobs, "%Y-%m-%dT%H:%M:%S")
                else:
                    try:
                        lastobs = datetime.strptime(lastobs, "%Y%m%d%H%M%S")
                    except:
                        lastobs = datetime.utcnow()
                form.cleaned_data['enddate'] = lastobs
            elif not form.cleaned_data['enddate']:
                form.cleaned_data['enddate'] = datetime.utcnow()
            obs, n, onlyrti, offset = fetch_observations(form.cleaned_data, lastobs)
            page_data['offset'] = offset
            page_data['lastobs'] = lastobs
            page_data['description'] = 'Search results (LCO)'
            page_data['searchstring'] = request.GET.get('query', None)

            page_data['n'] = n
            if n == 0:
                page_data['form'] = form
            elif obs['archive']:
                page_data['firstobs'] = obs['archive'][0]['DATE_OBS']
            elif obs['rti'] and not obs['archive']:
                page_data['firstobs'] = obs['rti'][0]['dateobs']

            page_data['obs'] = obs
            if page_data['slideshow']:
                return render(request, 'images/slideshow.html', page_data)
            else:
                return render(request, 'images/search.html', page_data)
        else:
            return render(request, 'images/search.html', {'form': form})


def fetch_observations(data, lastobs):
    obs = {'archive' : [], 'rti' : []}
    onlyrti = False
    rti_n = 0
    # earliest_obs = search_include_framedb(data['query'])
    offset = data.get('offset', 0)
    if not offset:
        offset = 0
    new_offset = offset+30
    if not data['enddate'] or data['enddate'] > datetime(2014, 4, 1):
        obs_archive  = search_archive(data, offset)
        if obs_archive:
            obs['archive'] = obs_archive['results']
            total_n = obs_archive['count']
    if len(obs['archive']) < n_per_page:
        # Fetch RTI images
        rti_obs = search_rtiarchive(data)
        rti_n = rti_obs.count()
        rti_obs = rti_obs[offset:new_offset]

        obs['rti'] = build_observations(rti_obs)
        total_n = len(obs['archive']) + rti_n
    if total_n == rti_n:
        onlyrti = True
    if obs['archive']:
        lastobs = obs['archive'][-1]['DATE_OBS']
    elif obs['rti'] and not obs['archive']:
        lastobs = obs['rti'][-1]['dateobs']
    else:
        lastobs = None
    return obs, total_n, onlyrti, new_offset


def search_include_framedb(objectname):
    query = "/find?tagid__in=LCOEPO,FTP&limit=1&order_by=date_obs&object_name=%s" % objectname
    details = framedb_lookup(query)
    if details:
        return details[0]['date_obs']
    else:
        return None


def get_site_data(code):
    # Store the TAG IDs in a config not here
    qstring = "SITEID=%s&limit=30&OBSTYPE=EXPOSE&RLEVEL=91" % (code)
    headers = get_auth_headers(settings.ARCHIVE_TOKEN_URL)
    obs = search_archive_data(qstring, headers)

    data = {'n': obs['count'],
            'obs': obs['results']}
    return data


def view_site(request, code, format=None):
    # Check we have a valid site
    if Site.objects.filter(code=code).count() == 0:

app/images/templates/images/archive_image.html
{% extends 'images/base.html' %}
{% load images_extras %}
{% load staticfiles %}
{% block header_script %}
<script type="text/javascript" src="{% static "js/rti_archive_observation.js" %}"></script>
<script type="text/javascript">
$(document).ready(function(){

var frame_id = {{frameid}}
var img_url;

  $.get("https://thumbnails.lco.global/"+ frame_id+"/?height=1000&width=1000", function(data){
    img_url = data.url;
    $('img.observation-image').attr('src',img_url);
    $('a.observation-image-link').attr('href', img_url)
    // Fix the download links after we have the IMG url
    $.get("https://archive-api.lco.global/frames/"+ frame_id+"/", function(data){
      var download_content = "<a href='"+ data.url+"' property='UCD:obs.image'>FITS</a> or <a href='"+ img_url+"' property='UCD:obs.image'>JPEG</a>";
      $('#download-link').html(download_content);
    });
  });

  $.get("https://thumbnails.lco.global/"+ frame_id+"/?height=1000&width=1000&color=true", function(data){
    img_url = data.url;
    $('#colour-version a').attr('href', img_url);
    $('#colour-version').show();
  });


});
</script>
{% endblock %}

{%block header %}{{ obs.OBJECT }}{%endblock%}

{%block title %}Observation of {{ obs.OBJECT }}{%endblock%}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="{% url 'home' %}">Observations</a></li>
  <li>{{ site }}</li>
  <li class="active">{{ obs.TELID }} : {{ obs.OBJECT }}</li>
</ol>

{% endblock %}

{% block main-content %}
        <a href='{{ obs.fullimage_url }}' title='Click for full size version' class="observation-image-link">
            <img src='http://lco.global/files/missing_large.png' class='observation-image img-responsive' alt='{{ obs.title }}' />
        </a>
        {% if otherobs%}
        <p class='moreobservations'>More observations by {{ obs.user }}:</p>
        <ul class='stream'>
            {% for ob in otherobs %}
            <li class='{{ ob.class }}'>
                <a href='{{ ob.url }}'>
                    <img src='{{ ob.thumb }}' alt='{{ ob.title }}' title='{{ ob.title }} taken on {{ ob.date }}'/>
                </a>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
{% endblock %}

{% block right_panel %}

<div class="panel panel-default">
  <div class="panel-heading">Observation Information</div>
            <table class='table table-condensed'>
                <tr style='display:none;'>
                    <td class='first'>Title:</td>
                    <td property='dc:title'>{{ obs.title }}</td>
                </tr>
                <tr>
                    <th scope="row">Date:</th>
                    <td>
                        <time property='UCD:time.creation'>{{ obs.DATE_OBS }}</time>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Coordinates:</th>
                    <td>
                        <span class='Spatial-ReferenceValue' title='{{ obs.RA }};{{ obs.DEC }}'>
                            <span property='UCD:pos.eq.RA' content='{{ obs.RA|hmstodegrees }}'>{{ obs.RA }}</span>,
                            <span property='UCD:pos.eq.DEC' content='{{ obs.DEC|dmstodegrees }}'>{{ obs.DEC }}</span>
                        </span>
                        <span class='Spatial-CoordinateFrame'>FK5</span>
                        <span class='Spatial-Equinox'>J2000</span>
                        <br />View this position in <a href='http://server1.wikisky.org/v2?ra={{ obs.RA|hmstohours }}&amp;de={{ obs.DEC|dmstodegrees }}&amp;zoom=10&amp;img_source=astrophoto' title="View these coordinates in Wikisky">Wikisky</a> or <a href='http://www.worldwidetelescope.org/wwtweb/goto.aspx?object=ViewShortcut&amp;ra={{ obs.RA|hmstohours }}&amp;dec={{ obs.DEC|dmstodegrees }}&amp;zoom=3' title="View these coordinates in Microsoft's World Wide Telescope">WorldWideTelescope</a>.
                    </td>
                </tr>
                <tr>
                    <th scope="row">Site:</th>
                    <td property='UCD:instr.tel'>{{site}}
                    </td>
                </tr>
                <tr>
                    <th scope="row">Filter:</th>
                    <td>{{ obs.FILTER|filters_lookup|safe }}</td>
                </tr>
                <tr>
                    <th scope="row">Exposure:</th>
                    <td>
                        <span property='UCD:obs.exposure'>{{ obs.EXPTIME|floatformat }}</span>s</td>
                </tr>
                <tr>
                    <th scope="row">Data:</th>
                    <td>
                        <div id="download-link">FITS data not currently available</div>
                        <p id="colour-version" style="display:none;">
                          <i class="fa fa-magic" aria-hidden="true"></i> <a href="">Color JPEG</a>
                        </p>
                        <div><i class="fa fa-info-circle" aria-hidden="true"></i>
 <a href="http://lco.global/education/observing/fpack/">Trouble with FITS files?</a></div>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Credit:</th>
                    <td>Image taken with a {{obs.TELID}} telescope at the {{site}} node of Las Cumbres Observatory</td>
                </tr>
                <tr>
                    <th scope="row">License:</th>
                    <td>
                        <a href="{{ obs.license }}" rel="license cc:license">
                            <img src="{% static "img/cc-by-nc.png" %}" style="height:1.5em;" title="Some rights reserved" />
                        </a>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Share:</th>
                    <td>
                        <a href="http://twitter.com/home/?status={{ obs.OBJECT|urlencode }}+@lco_global+{{site}}+node+http://{{ request.get_host }}{% url 'frame' frameid %}">
                            <i class="fa fa-twitter"></i>
                        </a>
                        <div class="fb-share-button" data-href="http://{{ request.get_host }}{% url 'frame' frameid %}" data-layout="button" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={{ request.get_host }}{% url 'frame' frameid %}%2F&amp;src=sdkpreparse">Share</a></div>
                        </a>
                    </td>
                </tr>
            </table>
          </div>
{% endblock %}

{% block alternate %}
        <div class="row">
          <div class="col-md-12">
            {{obs.other}}
          </div>
        </div>
{% endblock %}

app/images/templates/images/group.html
{% extends 'images/base.html' %}
{% load images_extras %}

{% block script-content %}{% endblock %}
{%block header %}{{ input.title }}{%endblock%}
{%block title %}{{ input.title }}{%endblock%}

{% block breadcrumb %}
								<ol class="breadcrumb">
									<li><a href="{% url 'home' %}">Observations</a></li>
									<li><a href="{% url 'home' %}{{ input.link }}">{{ input.title }}</a></li>
								</ol>
{% endblock %}

{% block telescopes-list-title %}{% endblock %}

{% block fullcontent %}
    <div class="container">
        <div class="row">
							<p>{{ input.description }}:</p>
						</div>
						<div class="row">
							<div class="time"></div>
							{% if pager %}
							<div class="pager">{{ pager|safe }}</div>
							{% endif %}
							<div>

							<div class='observation-results' data-json="{% url 'home' %}{% if link == 'recent' %}search{% else %}{{ link }}{% endif %}.json{% if input.pager.page > 1 %}?page={{input.pager.page}}{% endif %}" data-update="{% if link == 'recent' %}add{% else %}update{% endif %}" xmlns:dc='http://purl.org/dc/elements/1.1/' xmlns:UCD='http://www.ivoa.net/rdf/Vocabularies/UCD#'>
{% include "images/observationlist.html" with obs=obs %}
							</div>
						</div>
{% endblock %}

app/images/templates/images/search.html
{% extends 'images/list.html' %}
{% load static from staticfiles %}
{% load images_extras %}

{% block header %}{% if n >= 0 %}Results of your search{% if form.query != "" %} for {{ searchstring }}{% endif %}{% else %}Search public observations{% endif %}{%endblock%}
{% block title %}{% if n >= 0 %}Results of your search{% if form.query != "" %} for <em>&quot;{{ searchstring }}&quot;</em>{% endif %}{% else %}Search public observations{% endif %}{% endblock %}

{% block header_script %}
 <link rel="stylesheet" href="{% static "css/jquery-ui.css" %}">
 <script src="{% static "js/jquery-ui.min.js" %}"></script>
	<script>
	<!--
	$(document).ready(function(){
    $('.dates input').datepicker({
        format: "yyyy-mm-dd"
    });

    $('.archive-thumb-img img').each(function(i, el){
      var frameid= $(el).data('frameid');
      if (typeof(frameid) != 'undefined'){
        $.get("https://thumbnails.lco.global/"+ frameid+"/?height=200&width=200", function(data){
          img_url = data.url;
          $(el).attr('src',img_url);
        });
      }
     });

	});
	// -->
	</script>
{% endblock %}

{% if n >= 0 %}
{% block search %}
{% endblock %}
{% endif %}

{% block breadcrumb %}
              <ol class="breadcrumb">
							<li><a href="{% url 'home' %}">Observations</a></li>
              <li class="active">{% if n < 0 %}Search{% else %}<a href="{% url 'search' %}">Search</a> &raquo; Results{% endif %}</a></li>
            </ol>
{% endblock %}


{% block fullcontent %}
{% if n > 0 %}
<div class="container">
    <div class="row">
        <div class="col-md-6 col-xs-12">
        <form class="form-search" action="{% url 'search' %}" method='GET'>
          <div class = "input-group">
             <input class = "form-control"  placeholder="e.g. NGC 2020" name='query' type="text">
             <span class = "input-group-btn">
                <button class = "btn btn-default" type = "submit">
                   Search
                </button>
             </span>
          </div>
        </form>
        </div>
        <div class="col-sm-6 col-xs-12 col-lg-6" style='font-size:0.8em;'>[<a href="{% url 'search' %}">advanced search</a>]</div>
      </div>
    <div class="row">
			<p>{%if onlyrti %}There {% if n > 1 %}are{% else %}is{% endif %} {{ n }} observation{% if n > 1 %}s{% endif %}.{%else%}We found {{n}} observations. {% endif %}{% if n > 1 %} Newest observations are shown first.{% endif %}{% if avmcode %} You could also search for <a href="{% url 'show_avm' avm=avmcode %}">{{ avmname }}</a>.{% endif %}</p>
		</div>

		{% if pager %}
    <div class="row">
			<div class="pager">{{ pager|safe }}</div>
    </div>
				{% endif %}

    {% if obs.archive %}
    <div class="row">
      <h2>Recent Data</h2>
			<div class='observation-results' data-update="update" xmlns:dc='http://purl.org/dc/elements/1.1/' xmlns:UCD='http://www.ivoa.net/rdf/Vocabularies/UCD#'>
{% include "images/archive_obs_list.html" with obs=obs.archive %}
    </div>
    {% endif %}
    {% if obs.rti %}
    <div class="row">
      <h2>Older Data</h2>
			<div class='observation-results' data-update="update" xmlns:dc='http://purl.org/dc/elements/1.1/' xmlns:UCD='http://www.ivoa.net/rdf/Vocabularies/UCD#'>
{% include "images/observationlist.html" with obs=obs.rti %}
      </div>
    </div>
    {% endif %}

							<div class="pagination">
							    <span class="step-links">
							        <a href="{% url_add_query offset=offset %}"> Older observations &rarr;</a>
							    </span>
							</div>
						</div>
          </div>
{% else %}
		<div class="row">
      <div class="container">
{% if n == 0 %}
			<p>We found <strong>0</strong> results matching your search. Don't panic! Try making your search less specific.</p>
{% else %}
			<p>There are several ways to search through all our public observations. Use any combination of the options below to help narrow your search.</p>
{% endif %}

{% if form.errors %}
		{{form.errors}}
{% endif %}
    </div>
	</div>
			<div class="row">
        <div class="container">
          <form action="" method="get" id="rti-archive-form" class="form-horizontal" role="form">
            <div class="form-group">
              <label class="control-label col-sm-2" for="edit-ObName">Object Name:</label>
              <div class="col-sm-10">
                {{form.query}}
                <p class="help-block">The name of a single astronomical object e.g. &quot;<em>Orion Nebula</em>&quot;. This is a simple title search so <em>Saturn</em> would match both &quot;<em>Saturn</em>&quot; and &quot;<em>NGC7009 (Saturn Nebula)</em>&quot;.</p>
              </div>
            </div>

          <div class="form-group dates">
              <label class="control-label col-sm-2" for="id_alldates">Date range:</label>

            <div class="col-sm-5">
              <label for="startdate">Start date</label>
              <input type="text" class="form-control"  name="startdate" placeholder="Start date" value="{{form.startdate.value}}"/>
            </div>
            <div class="col-sm-5">
              <label for="enddate">End date</label>
              <input type=text class="form-control" name="enddate" placeholder="End date" value="{{form.enddate.value}}"/>
            {% if form.startdate.errors or form.enddate.errors %}<span class="error form-error">{{form.startdate.errors.as_text}} {{form.enddate.errors.as_text}}</span>{% endif %}
            <p class="help-block">Limit your search to a particular range of dates.</p>
          </div>
        </div>

					<input type="submit" name="submit" id="edit-submit" value="Search" class="btn btn-default btn-lg" />
      </form>
      </div>
		</div>
{% endif %}
{% endblock %}